@extends('layout')
@section('title', auth()->user()->isProfessional() ? 'Tableau de bord' : 'Mon espace patient')
@section('subtitle', 'Un regard sur les parcours, une attention pour chaque personne.')
@section('actions')@if(auth()->user()->isProfessional())<a href="/clients#nouveau" class="btn primary">@include('partials.icon',['name'=>'plus']) Nouveau patient</a>@endif @endsection
@section('content')
@php($professional = auth()->user()->isProfessional())
@if(!$professional && auth()->user()->client && !auth()->user()->client->hasConsent())<div class="panel consent-panel"><h3>Votre consentement, avant de commencer</h3><p>{{ config('psycho.consent_text') }}</p><form method="post" action="/consentement">@csrf<label class="check-label"><input type="checkbox" name="accepted" value="1" required> J’ai lu et j’accepte ce consentement (version {{ config('psycho.consent_version') }}).</label><button class="btn primary">Enregistrer mon consentement</button></form></div>@endif
<section class="welcome-banner"><div><span class="banner-tag"><span class="online-dot"></span> {{ $professional ? 'VOTRE ACTIVITÉ EN UN CLIN D’ŒIL' : 'VOTRE PARCOURS D’ACCOMPAGNEMENT' }}</span><h2>Bonjour {{ explode(' ',auth()->user()->name)[0] }},<br>chaque parcours mérite votre attention.</h2><p>{{ $professional ? 'Un espace pour comprendre, accompagner et faire grandir.' : 'Prenez le temps de répondre, à votre rythme et en toute confidentialité.' }}</p><a href="{{ $professional ? '/evaluations' : '#evaluations' }}" class="banner-link">{{ $professional ? 'Retrouver les évaluations' : 'Retrouver mes questionnaires' }} @include('partials.icon',['name'=>'arrow'])</a></div><div class="banner-art" aria-hidden="true"><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><div class="art-leaf leaf-one"></div><div class="art-leaf leaf-two"></div><div class="art-leaf leaf-three"></div><div class="art-stem"></div><div class="art-circle"><span>ψ</span></div><span class="art-star">✦</span></div></section>
<div class="stats-grid">
@foreach([[$professional?'Patients accompagnés':'Mon dossier',$clientCount,'users','teal','Un suivi personnalisé'],['Évaluations en cours',$assessments->where('status','en_cours')->count(),'clipboard','blue','Des parcours qui avancent'],['À réviser',$assessments->where('status','termine')->count(),'clock','amber','En attente de validation'],['Restitutions publiées',$assessments->where('status','publie')->count(),'check','purple','Des résultats partagés']] as [$label,$value,$icon,$color,$hint])<div class="stat-card"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon {{ $color }}">@include('partials.icon',['name'=>$icon])</span></div><strong class="stat-value">{{ $value }}</strong><small>{{ $hint }}</small></div>@endforeach
</div>
<div class="dashboard-grid"><section class="panel assessments-panel" id="evaluations"><div class="panel-heading"><div><h2>{{ $professional ? 'Évaluations récentes' : 'Mes évaluations' }}</h2><p>Suivez les prochaines étapes de chaque parcours.</p></div>@if($professional)<a class="text-link" href="/evaluations">Tout voir <span>↗</span></a>@endif</div><div class="table-wrap"><table><thead><tr><th>{{ $professional ? 'Patient' : 'Questionnaire' }}</th><th>Évaluation</th><th>Statut</th><th></th></tr></thead><tbody>
@forelse($assessments->take(6) as $a)<tr><td><div class="person"><span class="avatar soft">{{ mb_substr($a->client->first_name,0,1) }}{{ mb_substr($a->client->last_name,0,1) }}</span><span><strong>{{ $professional ? $a->client->full_name : $a->definition->name }}</strong><small>{{ $a->created_at->format('d/m/Y') }}</small></span></div></td><td>{{ $a->definition->name }}<small class="muted block">Version {{ $a->definition->version }}{{ $a->definition->is_demo ? ' · Démonstration' : '' }}</small></td><td>@include('partials.status',['status'=>$a->status])</td><td><a class="round-link" href="/evaluations/{{ $a->id }}" aria-label="Ouvrir l’évaluation de {{ $a->client->full_name }}">↗</a></td></tr>@empty<tr><td colspan="4" class="empty">Aucune évaluation pour le moment.</td></tr>@endforelse
</tbody></table></div></section>
<section class="panel appointments-panel"><div class="panel-heading"><div><h2>Prochains rendez-vous</h2><p>Le temps de l’échange.</p></div><span class="subtle-icon">@include('partials.icon',['name'=>'calendar'])</span></div><div class="appointment-list">@forelse($appointments as $a)<div class="appointment-item"><div class="date-tile"><strong>{{ $a->starts_at->format('d') }}</strong><span>{{ $a->starts_at->locale('fr')->isoFormat('MMM') }}</span></div><div><strong>{{ $a->title }}</strong><p>{{ $a->client->full_name }}</p><small>{{ $a->starts_at->format('H:i') }} · {{ $a->duration }} min</small></div><span class="schedule-dot"></span></div>@empty<div class="empty">Votre agenda est libre.</div>@endforelse</div><a href="/calendrier" class="panel-bottom-link">Ouvrir le calendrier @include('partials.icon',['name'=>'arrow'])</a></section></div>
<div class="bottom-grid"><section class="panel"><div class="panel-heading"><div><h2>Vue d’ensemble des parcours</h2><p>La progression des évaluations de votre espace.</p></div></div><div class="progress-overview">@php($total=max(1,$assessments->count())) @foreach([['en_cours','En cours','teal'],['termine','À réviser','amber'],['publie','Publiées','purple']] as [$key,$label,$color])<div class="progress-row"><span><i class="legend-dot {{ $color }}"></i>{{ $label }}</span><div class="progress-track"><div class="progress-fill {{ $color }}" style="width:{{ round($assessments->where('status',$key)->count()/$total*100) }}%"></div></div><strong>{{ $assessments->where('status',$key)->count() }}</strong></div>@endforeach</div></section><section class="care-card"><div class="care-icon">@include('partials.icon',['name'=>'shield'])</div><div><h3>Un cadre de confiance</h3><p>Les restitutions sont partagées uniquement après validation professionnelle. Chaque personne garde la maîtrise de son consentement.</p><a href="/profil" class="text-link">Mon espace et mes préférences ↗</a></div></section></div>
@endsection