<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/assets/brand.svg"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title', 'Tableau de bord') · Psychoévaluation</title><link rel="stylesheet" href="{{ asset('assets/app.css') }}"><script src="{{ asset('assets/app.js') }}" defer></script></head>
<body><div class="app-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="/"><span class="brand-icon">ψ</span><span>Psycho<span class="brand-light">évaluation</span><small>ESPACE CABINET</small></span></a>
<div class="cabinet-badge"><span class="mini-icon">✦</span><div>{{ auth()->user()->tenant->name }}<small>{{ auth()->user()->isProfessional() ? 'Accompagnement & suivi' : 'Votre espace sécurisé' }}</small></div><span class="online-dot"></span></div>
<nav aria-label="Navigation principale"><div class="nav-label">VOTRE ESPACE</div>
@php($links = auth()->user()->isProfessional() ? [['/','Tableau de bord','grid'],['/clients','Patients','users'],['/organisations','Organisations','building'],['/evaluations','Évaluations','clipboard'],['/questionnaires','Questionnaires','layers'],['/calendrier','Calendrier','calendar']] : [['/','Mon espace','grid'],['/calendrier','Mes rendez-vous','calendar']])
@foreach($links as [$url,$label,$icon])
@if(!(auth()->user()->role === 'entreprise' && $url === '/calendrier'))<a href="{{ $url }}" class="nav-item {{ request()->is($url === '/' ? '/' : trim($url,'/').'*') ? 'active' : '' }}">@include('partials.icon',['name'=>$icon]) {{ $label }}</a>@endif
@endforeach
@if(config('patientai.enabled') && auth()->user()->role === 'patient' && auth()->user()->client)
<a href="{{ route('patientai.index') }}" class="nav-item">✨ PatientAI</a>
@endif
<div class="nav-label">COLLABORATION</div>
@foreach([['/messagerie','Messagerie','message'],['/documents','Documents','folder']] as [$url,$label,$icon])<a href="{{ $url }}" class="nav-item {{ request()->is(trim($url,'/').'*') ? 'active' : '' }}">@include('partials.icon',['name'=>$icon]) {{ $label }}</a>@endforeach
@if(auth()->user()->isProfessional())
@foreach([['/comparateur','Comparateur','chart'],['/courriers','Courriers','mail'],['/espace-travail','Espace de travail','edit'],['/guide','Guide Ennéagramme','book']] as [$url,$label,$icon])<a href="{{ $url }}" class="nav-item {{ request()->is(trim($url,'/').'*') ? 'active' : '' }}">@include('partials.icon',['name'=>$icon]) {{ $label }}</a>@endforeach
<div class="nav-label">GESTION</div>
@if(auth()->user()->role === 'admin')<a href="/administration" class="nav-item {{ request()->is('administration*') ? 'active' : '' }}">@include('partials.icon',['name'=>'settings']) Administration</a>@endif
@if(auth()->user()->canPublish())<a href="/droits" class="nav-item">@include('partials.icon',['name'=>'shield']) Droits & conservation</a><a href="/corbeille" class="nav-item {{ request()->is('corbeille*') ? 'active' : '' }}">@include('partials.icon',['name'=>'trash']) Corbeille</a>@endif
@endif</nav><div class="sidebar-bottom"><span class="online-dot"></span> Espace privé et sécurisé<small>Les données restent dans votre cabinet.</small></div></aside>
<div class="main-shell"><header class="topbar"><button class="icon-button mobile-menu" aria-label="Afficher le menu" data-menu>☰</button><div class="breadcrumb">Mon cabinet <span>/</span> <strong>@yield('title', 'Tableau de bord')</strong></div><div class="topbar-right"><span class="today">{{ now()->locale('fr')->isoFormat('D MMMM YYYY') }}</span><div class="top-divider"></div><a class="profile" href="/profil"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><span>{{ auth()->user()->name }}<small>{{ ucfirst(auth()->user()->role) }}</small></span></a><form method="post" action="/deconnexion">@csrf<button class="icon-button" title="Se déconnecter" aria-label="Se déconnecter">@include('partials.icon',['name'=>'logout'])</button></form></div></header>
<main id="main"><div class="page-heading"><div><div class="eyebrow">@yield('eyebrow', 'UN SUIVI ATTENTIF, À CHAQUE ÉTAPE')</div><h1>@yield('title', 'Tableau de bord')</h1><p>@yield('subtitle', 'Retrouvez l’essentiel de votre activité et accompagnez chaque parcours.')</p></div><div class="page-actions">@yield('actions')</div></div>
@if(session('success'))<div class="alert success" role="status">✓ {{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error" role="alert"><strong>Vérifiez les informations suivantes.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')<footer class="page-footer"><span>Psychoévaluation <span class="dot">·</span> L’humain au cœur du suivi</span><span>Confidentialité & accompagnement</span></footer></main></div></div></body></html>