<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AssessmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BrandingController;
use App\Http\Controllers\CabinetController;
use App\Http\Controllers\DefinitionController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\PatientAiController;
use App\Http\Controllers\PrivacyController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::view('/mot-de-passe-oublie', 'auth.forgot')->name('password.request');
    Route::post('/mot-de-passe-oublie', [AccountController::class, 'forgot'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/reinitialiser/{token}', [AccountController::class, 'resetForm'])->name('password.reset');
    Route::post('/reinitialiser', [AccountController::class, 'reset'])->middleware('throttle:5,1')->name('password.update');
    Route::get('/invitation/{token}', [AccountController::class, 'invitation'])->middleware('throttle:20,1');
    Route::post('/invitation/{token}', [AccountController::class, 'accept'])->middleware('throttle:5,1');
    Route::view('/connexion', 'auth.login')->name('login');
    Route::post('/connexion', [AuthController::class, 'login'])->middleware('throttle:5,1');
});
Route::middleware('auth')->group(function () {
    Route::prefix('patient/assistant')->name('patientai.')->group(function (): void {
        Route::get('/', [PatientAiController::class, 'index'])->name('index');
        Route::post('/', [PatientAiController::class, 'store'])->middleware('throttle:patientai')->name('store');
        Route::delete('/memory', [PatientAiController::class, 'clearMemory'])->middleware('throttle:patientai')->name('memory.clear');
        Route::get('/{conversation}', [PatientAiController::class, 'show'])->name('show');
        Route::post('/{conversation}/messages', [PatientAiController::class, 'message'])->middleware('throttle:patientai')->name('message');
        Route::delete('/{conversation}', [PatientAiController::class, 'destroy'])->name('destroy');
    });
    Route::post('/administration/invitations', [AccountController::class, 'invite']);
    Route::post('/administration/invitations/{invitation}/renvoyer', [AccountController::class, 'resend']);
    Route::post('/administration/invitations/{invitation}/revoquer', [AccountController::class, 'revoke']);
    Route::put('/administration/utilisateurs/{user}/role', [AccountController::class, 'role']);
    Route::get('/administration/boite-test', [AccountController::class, 'mailbox']);
    Route::post('/administration/logo', [BrandingController::class, 'store']);
    Route::delete('/administration/logo', [BrandingController::class, 'destroy']);
    Route::get('/courriers/{letter}/archive', [ModuleController::class, 'letterBundle']);
    Route::get('/questionnaires/{definition}/export', [DefinitionController::class, 'export']);
    Route::get('/droits', [PrivacyController::class, 'index']);
    Route::post('/profil/demandes', [PrivacyController::class, 'request']);
    Route::post('/droits/demandes/{privacyRequest}', [PrivacyController::class, 'resolve']);
    Route::get('/droits/clients/{id}/export', [PrivacyController::class, 'export']);
    Route::post('/droits/clients/{id}/conservation', [PrivacyController::class, 'hold']);
    Route::post('/droits/clients/{id}/effacer', [PrivacyController::class, 'erase']);
    Route::post('/deconnexion', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', [CabinetController::class, 'dashboard'])->name('dashboard');
    Route::view('/profil', 'modules.profile')->name('profile');
    Route::post('/profil/mot-de-passe', [AuthController::class, 'password'])->middleware('throttle:5,1');
    Route::post('/consentement', [CabinetController::class, 'consent']);
    Route::post('/consentement/retrait', [CabinetController::class, 'revoke']);
    Route::get('/clients', [CabinetController::class, 'clients'])->name('clients.index');
    Route::post('/clients', [CabinetController::class, 'saveClient']);
    Route::get('/clients/{client}', [CabinetController::class, 'client'])->name('clients.show');
    Route::put('/clients/{client}', [CabinetController::class, 'saveClient']);
    Route::delete('/clients/{client}', [CabinetController::class, 'archive']);
    Route::post('/clients/{client}/notes', [CabinetController::class, 'note']);
    Route::get('/organisations', [CabinetController::class, 'organizations']);
    Route::post('/organisations', [CabinetController::class, 'organization']);
    Route::get('/evaluations', [AssessmentController::class, 'index'])->name('evaluations.index');
    Route::post('/evaluations', [AssessmentController::class, 'assign']);
    Route::get('/evaluations/{assessment}', [AssessmentController::class, 'show'])->name('evaluations.show');
    Route::put('/evaluations/{assessment}/reponses', [AssessmentController::class, 'answers']);
    Route::post('/evaluations/{assessment}/interpretation', [AssessmentController::class, 'interpretation']);
    Route::post('/evaluations/{assessment}/publier', [AssessmentController::class, 'publish']);
    Route::post('/evaluations/{assessment}/depublier', [AssessmentController::class, 'unpublish']);
    Route::post('/evaluations/{assessment}/ia', [AssessmentController::class, 'ai'])->middleware('throttle:5,1');
    Route::get('/evaluations/{assessment}/pdf', [AssessmentController::class, 'pdf'])->name('evaluations.pdf');
    Route::get('/questionnaires', [DefinitionController::class, 'index']);
    Route::post('/questionnaires', [DefinitionController::class, 'store']);
    Route::get('/calendrier', [ModuleController::class, 'calendar'])->name('calendar.index');
    Route::post('/calendrier', [ModuleController::class, 'appointment']);
    Route::post('/calendrier/{appointment}/annuler', [ModuleController::class, 'cancel']);
    Route::get('/messagerie', [ModuleController::class, 'messages'])->name('messages.index');
    Route::post('/messagerie', [ModuleController::class, 'send']);
    Route::get('/documents', [ModuleController::class, 'documents'])->name('documents.index');
    Route::post('/documents', [ModuleController::class, 'upload']);
    Route::get('/documents/{document}/lien', [ModuleController::class, 'documentLink']);
    Route::get('/documents/{document}/telecharger', [ModuleController::class, 'download'])->middleware('signed')->name('documents.download');
    Route::get('/courriers', [ModuleController::class, 'letters']);
    Route::post('/courriers', [ModuleController::class, 'letter']);
    Route::get('/courriers/{letter}/pdf', [ModuleController::class, 'letterPdf']);
    Route::get('/comparateur', [ModuleController::class, 'compare']);
    Route::post('/comparateur', [ModuleController::class, 'comparison']);
    Route::get('/comparateur/{comparison}/pdf', [ModuleController::class, 'comparisonPdf']);
    Route::get('/espace-travail', [ModuleController::class, 'workspace']);
    Route::post('/espace-travail', [ModuleController::class, 'workspaceSave']);
    Route::view('/guide', 'modules.guide');
    Route::get('/corbeille', [CabinetController::class, 'trash']);
    Route::post('/corbeille/{id}/restaurer', [CabinetController::class, 'restore']);
    Route::get('/administration', [CabinetController::class, 'admin'])->name('administration');
    Route::post('/administration/utilisateurs', [CabinetController::class, 'user'])->name('administration.users.store');
    Route::post('/administration/utilisateurs/{user}/acces', [CabinetController::class, 'toggleUser']);
    Route::post('/administration/cabinet', [CabinetController::class, 'settings']);
});
