@extends('layout') @section('title',$assessment->definition->name) @section('subtitle',$assessment->client->full_name.' · Version '.$assessment->definition->version.' · '.$assessment->definition->engine_version)
@section('actions')@include('partials.status',['status'=>$assessment->status]) @if(auth()->user()->isProfessional() || $assessment->status==='publie')<a class="btn secondary" href="/evaluations/{{ $assessment->id }}/pdf">Télécharger le PDF</a>@endif @endsection
@section('content')
@if($assessment->definition->is_demo)<div class="alert info">Questionnaire de démonstration. Il ne constitue pas un instrument psychométrique validé.</div>@endif
<div class="workflow"><span class="done">1. Assignation</span><span class="{{ $assessment->status!=='en_cours'?'done':'current' }}">2. Passation</span><span class="{{ $assessment->status==='termine'?'current':'' }}">3. Révision</span><span class="{{ $assessment->status==='publie'?'done':'' }}">4. Publication</span></div>
@if(auth()->user()->role==='patient' && $assessment->status==='en_cours')
@if(!$assessment->client->hasConsent())<div class="panel form-panel"><h2>Consentement requis</h2><p>Acceptez le consentement dans votre espace avant de commencer.</p><a class="btn primary" href="/">Retour à mon espace</a></div>@else
<section class="panel form-panel"><div class="panel-heading flush"><div><h2>Votre questionnaire</h2><p>Répondez à votre rythme. Vous pouvez reprendre plus tard.</p></div><span class="save-status" aria-live="polite" data-save-status>Sauvegarde automatique active</span></div><form action="/evaluations/{{ $assessment->id }}/reponses" method="post" data-autosave>@csrf @method('PUT')
@foreach($assessment->definition->questions as $q)@php($value=old('answers.'.$q['id'],$assessment->answers[$q['id']]??null))<fieldset class="question"><legend><span class="question-number">{{ $loop->iteration }}</span>{{ $q['label'] }}{{ ($q['required']??true)?' *':'' }}</legend>
@if($q['type']==='boolean')<div class="choice-row">@foreach(['1'=>'Oui','0'=>'Non'] as $v=>$label)<label class="choice"><input type="radio" name="answers[{{ $q['id'] }}]" value="{{ $v }}" @checked($value!==null && (int)$value===(int)$v)> {{ $label }}</label>@endforeach</div>
@elseif($q['type']==='choice')<select name="answers[{{ $q['id'] }}]" aria-label="{{ $q['label'] }}"><option value="">Choisir une réponse</option>@foreach($q['options'] as $option)<option @selected($value===$option)>{{ $option }}</option>@endforeach</select>
@elseif($q['type']==='scale')<label class="scale-label">Valeur de {{ $q['min'] }} à {{ $q['max'] }}<input type="number" name="answers[{{ $q['id'] }}]" min="{{ $q['min'] }}" max="{{ $q['max'] }}" value="{{ $value }}" step="1"></label>
@else<textarea name="answers[{{ $q['id'] }}]" rows="3" maxlength="5000" aria-label="{{ $q['label'] }}">{{ $value }}</textarea>@endif</fieldset>@endforeach<div class="form-actions"><button class="btn secondary" name="submit" value="0">Sauvegarder</button><button class="btn primary" name="submit" value="1" data-submit-final>Soumettre définitivement</button></div><p class="muted">La soumission verrouille vos réponses. Une nouvelle passation nécessite une nouvelle assignation.</p></form></section>@endif
@else
@if(auth()->user()->isProfessional() || ($assessment->status==='publie' && $assessment->interpretation?->published_at))
@if($assessment->results)<section class="panel form-panel"><h2>Résultats de la passation</h2>@include('evaluations.results',['results'=>$assessment->results])</section>@endif
@if(auth()->user()->isProfessional())<section class="panel form-panel"><h2>Réponses enregistrées</h2>@foreach($assessment->definition->questions as $q)<div class="answer-row"><strong>{{ $q['label'] }}</strong><p>{{ isset($assessment->answers[$q['id']]) ? (is_bool($assessment->answers[$q['id']]) ? ($assessment->answers[$q['id']] ? 'Oui':'Non') : $assessment->answers[$q['id']]) : 'Sans réponse' }}</p></div>@endforeach</section>@endif
@else<div class="panel form-panel"><h2>Merci pour vos réponses</h2><p>Votre professionnel prépare votre restitution. Elle apparaîtra ici après validation et publication.</p></div>@endif
@endif
@if($assessment->interpretation?->published_at)<section class="panel form-panel"><div class="panel-heading flush"><h2>Restitution publiée</h2><span class="badge publie">Validée le {{ $assessment->interpretation->published_at->format('d/m/Y') }}</span></div><div class="prose">{!! \Illuminate\Support\Str::markdown($assessment->interpretation->published_content,['html_input'=>'strip','allow_unsafe_links'=>false]) !!}</div></section>@endif
@if(auth()->user()->canPublish() && $assessment->status!=='en_cours')<section class="panel form-panel"><h2>Révision professionnelle</h2><p class="muted">Le brouillon est privé. La publication est une action distincte.</p><form method="post" action="/evaluations/{{ $assessment->id }}/interpretation">@csrf<label>Brouillon d’interprétation (Markdown)<textarea rows="12" name="draft" required maxlength="50000">{{ old('draft',$assessment->interpretation?->draft) }}</textarea></label><button class="btn secondary">Enregistrer le brouillon</button></form><div class="divider"></div><form method="post" action="/evaluations/{{ $assessment->id }}/publier" data-confirm="Publier le dernier brouillon enregistré dans le portail patient ?">@csrf<label class="check-label"><input type="checkbox" name="reviewed" value="1" required> J’ai relu et validé le dernier brouillon enregistré.</label><button class="btn primary">Valider et publier</button></form>@if($assessment->interpretation?->published_at)<form method="post" action="/evaluations/{{ $assessment->id }}/depublier">@csrf<button class="btn danger">Retirer la publication</button></form>@endif</section><section class="panel form-panel"><h2>Assistance à la rédaction par IA</h2><p class="muted">{{ config('psycho.ai_enabled') ? 'Seuls le type de test et les scores structurés sont transmis au fournisseur configuré. Le brouillon existant sera remplacé ; le contenu publié reste inchangé.' : 'Fonction désactivée. Configurez un fournisseur et ses conditions d’utilisation avant de l’activer.' }}</p>@if(config('psycho.ai_enabled'))<form method="post" action="/evaluations/{{ $assessment->id }}/ia">@csrf<label class="check-label"><input type="checkbox" name="authorized" value="1" required> J’atteste disposer de l’autorisation nécessaire pour cette transmission.</label><button class="btn secondary">Générer un brouillon IA</button></form>@endif</section>@endif
@include('evaluations.ai-history')
@include('partials.history')
@endsection